-- CreateTable
CREATE TABLE "DiagnosisCode" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "parentCode" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DiagnosisCode_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "DiagnosisCode_code_key" ON "DiagnosisCode"("code");
CREATE INDEX "DiagnosisCode_code_idx" ON "DiagnosisCode"("code");
CREATE INDEX "DiagnosisCode_parentCode_idx" ON "DiagnosisCode"("parentCode");

-- Seed ICD-10 K00-K10 Dental Diagnosis Codes
INSERT INTO "DiagnosisCode" ("id", "code", "description", "parentCode", "updatedAt") VALUES
('dc_k00',   'K00',   'Diş çıkması ve gelişimi bozuklukları', NULL, NOW()),
('dc_k000',  'K00.0', 'Anodonti', 'K00', NOW()),
('dc_k001',  'K00.1', 'Fazla sayıda dişler', 'K00', NOW()),
('dc_k002',  'K00.2', 'Dişlerin büyüklük ve şekil anomalileri', 'K00', NOW()),
('dc_k003',  'K00.3', 'Diş renklenmeleri', 'K00', NOW()),
('dc_k004',  'K00.4', 'Diş oluşum bozuklukları', 'K00', NOW()),
('dc_k005',  'K00.5', 'Dişlerin yapısında herediter bozukluklar, başka yerde sınıflanmamış', 'K00', NOW()),
('dc_k006',  'K00.6', 'Diş çıkmasındaki bozukluklar', 'K00', NOW()),
('dc_k007',  'K00.7', 'Teething sendromu', 'K00', NOW()),
('dc_k008',  'K00.8', 'Diş gelişiminin diğer bozuklukları', 'K00', NOW()),
('dc_k009',  'K00.9', 'Diş gelişim bozukluğu, tanımlanmamış', 'K00', NOW()),
('dc_k01',   'K01',   'Gömülü ve sıkışık dişler', NULL, NOW()),
('dc_k010',  'K01.0', 'Gömülü diş', 'K01', NOW()),
('dc_k011',  'K01.1', 'Sıkışık diş', 'K01', NOW()),
('dc_k02',   'K02',   'Diş çürükleri', NULL, NOW()),
('dc_k020',  'K02.0', 'Mine çürüğü', 'K02', NOW()),
('dc_k021',  'K02.1', 'Dentin çürüğü', 'K02', NOW()),
('dc_k022',  'K02.2', 'Sement çürüğü', 'K02', NOW()),
('dc_k023',  'K02.3', 'Durmuş dental çürükler', 'K02', NOW()),
('dc_k024',  'K02.4', 'Odontoklazi', 'K02', NOW()),
('dc_k028',  'K02.8', 'Diş çürükleri, diğer', 'K02', NOW()),
('dc_k029',  'K02.9', 'Diş çürüğü, tanımlanmamış', 'K02', NOW()),
('dc_k03',   'K03',   'Diş sert dokusunun diğer hastalıkları', NULL, NOW()),
('dc_k030',  'K03.0', 'Dişin atrizyonu', 'K03', NOW()),
('dc_k031',  'K03.1', 'Diş abrazyonu', 'K03', NOW()),
('dc_k032',  'K03.2', 'Diş erozyonu', 'K03', NOW()),
('dc_k033',  'K03.3', 'Dişin patolojik rezorpsiyonu', 'K03', NOW()),
('dc_k034',  'K03.4', 'Hipersementozis', 'K03', NOW()),
('dc_k035',  'K03.5', 'Diş ankilozu', 'K03', NOW()),
('dc_k036',  'K03.6', 'Dişte birikimler [accretions]', 'K03', NOW()),
('dc_k037',  'K03.7', 'Dişin sert dokusunun diş çıktıktan sonrası renk değişikliği', 'K03', NOW()),
('dc_k038',  'K03.8', 'Dişin sert dokusunun diğer tanımlanmış hastalıkları', 'K03', NOW()),
('dc_k039',  'K03.9', 'Diş sert dokularının hastalığı, tanımlanmamış', 'K03', NOW()),
('dc_k04',   'K04',   'Pulpa ve periapikal dokuların hastalığı', NULL, NOW()),
('dc_k040',  'K04.0', 'Pulpit', 'K04', NOW()),
('dc_k041',  'K04.1', 'Pulpa nekrozu', 'K04', NOW()),
('dc_k042',  'K04.2', 'Pulpa dejenerasyonu', 'K04', NOW()),
('dc_k043',  'K04.3', 'Pulpada anormal sert doku oluşumu', 'K04', NOW()),
('dc_k044',  'K04.4', 'Pulpal kaynaklı akut apikal periodontit', 'K04', NOW()),
('dc_k045',  'K04.5', 'Kronik apikal periodontit', 'K04', NOW()),
('dc_k046',  'K04.6', 'Periapikal apse, sinüs oluşumuyla birlikte', 'K04', NOW()),
('dc_k047',  'K04.7', 'Periapikal apse, sinüs oluşumu olmadan', 'K04', NOW()),
('dc_k048',  'K04.8', 'Radiküler kist', 'K04', NOW()),
('dc_k049',  'K04.9', 'Pulpa ve periapikal dokuların diğer ve tanımlanmamış hastalıkları', 'K04', NOW()),
('dc_k05',   'K05',   'Gingivit ve periodontal hastalıklar', NULL, NOW()),
('dc_k050',  'K05.0', 'Akut gingivit', 'K05', NOW()),
('dc_k051',  'K05.1', 'Kronik gingivit', 'K05', NOW()),
('dc_k052',  'K05.2', 'Akut periodontit', 'K05', NOW()),
('dc_k053',  'K05.3', 'Kronik periodontit', 'K05', NOW()),
('dc_k054',  'K05.4', 'Periodontoz', 'K05', NOW()),
('dc_k055',  'K05.5', 'Periodontal hastalıklar, diğer', 'K05', NOW()),
('dc_k056',  'K05.6', 'Periodontal hastalık, tanımlanmamış', 'K05', NOW()),
('dc_k06',   'K06',   'Gingiva ve edentüloz alveoler kenar diğer bozuklukları', NULL, NOW()),
('dc_k060',  'K06.0', 'Gingival gerileme', 'K06', NOW()),
('dc_k061',  'K06.1', 'Gingival büyüme', 'K06', NOW()),
('dc_k062',  'K06.2', 'Gingival ve edentülöz alveolar ridge lezyonları, travma ile beraber', 'K06', NOW()),
('dc_k068',  'K06.8', 'Gingiva ve edentülöz alveoler ridge diğer tanımlanmış bozuklukları', 'K06', NOW()),
('dc_k069',  'K06.9', 'Gingiva ve edentülöz alveoler ridge bozukluğu, tanımlanmamış', 'K06', NOW()),
('dc_k07',   'K07',   'Dentofasyal anomaliler [malokluzyon dahil]', NULL, NOW()),
('dc_k070',  'K07.0', 'Çene büyüklüğünün ana anomalileri', 'K07', NOW()),
('dc_k071',  'K07.1', 'Çene-kafa kaidesi anomalileri', 'K07', NOW()),
('dc_k072',  'K07.2', 'Diş arkı anomalileri', 'K07', NOW()),
('dc_k073',  'K07.3', 'Diş pozisyon anomalileri', 'K07', NOW()),
('dc_k074',  'K07.4', 'Maloklüzyon, tanımlanmamış', 'K07', NOW()),
('dc_k075',  'K07.5', 'Dentofasiyal fonksiyonal anomaliler', 'K07', NOW()),
('dc_k076',  'K07.6', 'Temporomandibüler eklem bozuklukları', 'K07', NOW()),
('dc_k078',  'K07.8', 'Dentofasiyal anomaliler, diğer', 'K07', NOW()),
('dc_k079',  'K07.9', 'Dentofasiyal anomali, tanımlanmamış', 'K07', NOW()),
('dc_k08',   'K08',   'Dişler ve destekleyici yapıların diğer hastalıkları', NULL, NOW()),
('dc_k080',  'K08.0', 'Dişlerin eksfoliasyonu; sistemik sebeplerden dolayı', 'K08', NOW()),
('dc_k081',  'K08.1', 'Diş kaybı; kaza, çekim veya lokal periodontal hastalıktan dolayı', 'K08', NOW()),
('dc_k082',  'K08.2', 'Edentülöz alveoler kenar atrofisi', 'K08', NOW()),
('dc_k083',  'K08.3', 'Gömülü diş kökü', 'K08', NOW()),
('dc_k088',  'K08.8', 'Dişler ve destekleyici yapıların diğer tanımlanmış bozuklukları', 'K08', NOW()),
('dc_k089',  'K08.9', 'Dişler ve destekleyici yapıların bozukluğu, tanımlanmamış', 'K08', NOW()),
('dc_k09',   'K09',   'Oral bölge kistleri, başka yerde sınıflanmamış', NULL, NOW()),
('dc_k090',  'K09.0', 'Gelişimsel odontojenik kistler', 'K09', NOW()),
('dc_k091',  'K09.1', 'Oral bölge gelişimsel (nonodontojenik) kistleri', 'K09', NOW()),
('dc_k092',  'K09.2', 'Çene kistleri, diğer', 'K09', NOW()),
('dc_k098',  'K09.8', 'Oral bölge diğer kistleri, başka yerde sınıflanmamış', 'K09', NOW()),
('dc_k099',  'K09.9', 'Oral bölge kisti, tanımlanmamış', 'K09', NOW()),
('dc_k10',   'K10',   'Çenenin diğer hastalıkları', NULL, NOW()),
('dc_k100',  'K10.0', 'Çenenin gelişimsel bozuklukları', 'K10', NOW()),
('dc_k101',  'K10.1', 'Dev hücreli granülom, merkezi', 'K10', NOW()),
('dc_k102',  'K10.2', 'Çenenin enflamatuvar durumları', 'K10', NOW()),
('dc_k103',  'K10.3', 'Çene alveoliti', 'K10', NOW()),
('dc_k108',  'K10.8', 'Çenenin diğer tanımlanmış hastalıkları', 'K10', NOW()),
('dc_k109',  'K10.9', 'Çene hastalığı, tanımlanmamış', 'K10', NOW())
ON CONFLICT ("code") DO NOTHING;
